packages:
  - webapp
  - server
  # exclude packages that are inside test directories
  - '!**/test/**'
  # all packages in subdirs of components/
  - 'components/**'
allowBuilds:
  '@prisma/engines': true
  better-sqlite3: true
  esbuild: true
  prisma: true
